main/urls.py
from django.conf.urls import url

from main import views

app_name = 'main'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^update_tasks$', views.get_tasks, name='update_tasks'),
    url(r'^create_task$', views.create_task, name='create_task'),
    url(r'^search$', views.search, name='search'),
]

to_do_list/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

class Task(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

main/views.py
from django.http import response
from django.shortcuts import render, render_to_response

from main.models import Task


def index(request):
    return render(request, 'main/index.html')

def create_task(request):
    if request.method == 'POST' and request.POST['name'] and request.POST['description']:
        task = Task(name=request.POST.get('name'), description=request.POST.get('description'))
        task.save()
        return response.HttpResponse('success')
    return response.HttpResponse('request is empty')


def get_tasks(request):
    context = {
        'tasks': Task.objects.all().order_by('-id')
    }
    return render_to_response('main/list.html', context)

def search(request):
    text = request.GET.get('text')
    if len(text.strip()) > 3:
        context = {
            'tasks': Task.objects.filter(name__contains=text.strip())
        }
        return render_to_response('main/search_results.html', context)
    return response.HttpResponse('Должно быть не меньше 3 символов')

main/templates/main/index.html
{% extends 'base.html' %}


{% block content %}
    <div class="row">
        <div class="col-lg-4">
            <form id="task" class="form-row">
                <input class="form-control" name="name" type="text" placeholder="Название">
                <textarea class="form-control" name="description" placeholder="Описание" rows="5"></textarea>
            </form>
            <br>
            <button class="btn btn-primary" onclick="createTask()">Создать</button>

        </div>
        <div class="col-lg-8">
            <input id="search" class="form-control" name="text" type="text" placeholder="Поиск по названию">
            <br>
            <button class="btn btn-primary" onclick="search_task()">Поиск</button>
            <div id="result"></div>
        </div>
    </div><br>
    <div id="list" class="col-lg-12">
    </div>
    <script type="text/javascript">
        function createTask() {
            var name = $("#task input").val();
            var description = $("#task textarea").val();
            $.ajax({
                type: 'POST',
                url: "{% url 'main:create_task' %}",
                data: {
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    name: name,
                    description: description
                },
                success: function () {
                    $("#task input").val('');
                    $("#task textarea").val('');
                    updateTasks();
                }
            });
        }

        function updateTasks() {
            $.ajax({
                type: 'GET',
                url: "{% url 'main:update_tasks' %}",
                success: function (html) {
                    $("#list").html(html);
                }
            });
        }

        function search_task() {
            var data = $("#search").serialize();
            $.ajax({
                type: 'GET',
                url: "{% url 'main:search' %}",
                data: data,
                success: function (html) {
                    $("#result").html(html);
                }
            });
        }

        $(document).ready(function () {
            updateTasks();
        })
    </script>
{% endblock %}

main/templates/main/list.html
<table class="table">
    <th>Название</th>
    <th>Описание</th>
    {% for task in tasks %}
        <tr>
            <td>{{ task.name }}</td>
            <td>{{ task.description }}</td>
        </tr>
    {% endfor %}
</table>

main/templates/main/search_results.html
<table class="table">
    {% for task in tasks %}
        <tr>
            <td>{{ task.name|truncatechars:20 }}</td>
            <td>{{ task.description|truncatechars:40 }}</td>
        </tr>
    {% endfor %}
</table>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <title>Список задач</title>
</head>
<body>
<div class="container">
    <h2>Список задач</h2><br>
{% block content %}
{% endblock %}
</div>
</body>
</html>